### ISSUE TITLE
"cargo local-pkgs clean" doesn't clean

### ISSUE THREAD

**Issue by Lakier15** [jonas-schievink/cargo-local-pkgs#4]
I am having a problem with
```sh
cargo local-pkgs clean
```

I have got .lock files (I even tried to regenerate them), my main crate references those crates in cargo.toml, however, the "target" folders in my subcrates are not deleted.

cargo-local-pkgs v0.3.2
cargo 0.21.0-nightly (50b1c24d1 2017-06-17)

**Comment by jonas-schievink** [comment]
That command will essentially run `cargo clean -p <package>` for all packages it finds, which only deletes the final artifacts, not the whole target directory.

I suggest trying just `cargo clean` if it works for you. Otherwise, consider using Cargo workspaces and try `cargo clean` then.

**Comment by Lakier15** [comment]
Will I be able to run other commands with cargo-local-pkgs when I will be using cargo workspaces?

Otherwise I might resort into writing a shell script to discover crates and xargs cargo clean in every crate directory.

**Comment by jonas-schievink** [comment]
local-pkgs was developed back when workspaces were not a thing, so I don't know. Actually, workspaces and the --all flag most cargo operations take are intended to replace this crate. If they aren't sufficient for your use case you might want to open a cargo issue.

**Comment by Lakier15** [comment]
Ok, now is all clear.
Thanks!
